import { Composer } from "grammy";
import type { Ctx } from "../bot.js";
import { forceReply, GalleryStore, gallerySession, notifyOwner, normalizeTag } from "../gallery.js";
import { adminChatId, inlineButton, inlineKeyboard, registerMainMenuItem, requireOwner, type OwnerAwareCtx } from "../toolkit/index.js";
registerMainMenuItem({ label: "Manage gallery", data: "admin:menu", order: 30 });
const composer = new Composer<Ctx>();
const adminKeys = inlineKeyboard([[inlineButton("Create album", "admin:create"), inlineButton("Seed albums", "admin:seed")], [inlineButton("Upload photos", "admin:upload")], [inlineButton("Edit photos", "admin:edit")], [inlineButton("Delete album", "admin:delete-album")], [inlineButton("Notifications", "admin:notifications")], [inlineButton("Albums", "gallery:albums")]]);
async function owner(ctx: Ctx): Promise<boolean> { return requireOwner(ctx as unknown as OwnerAwareCtx); }
async function menu(ctx: Ctx, edit = false) { if (!(await owner(ctx))) return; const text = "Your gallery tools are ready."; if (edit) await ctx.editMessageText(text, { reply_markup: adminKeys }); else await ctx.reply(text, { reply_markup: adminKeys }); }
async function albumPicker(ctx: Ctx, action: "upload" | "edit" | "delete") { const store = await GalleryStore.open(ctx); if (!store) return ctx.reply("Gallery storage isn't set up yet."); const albums = await store.albums(); if (!albums.length) return ctx.reply("No albums yet — create one first."); await ctx.editMessageText("Choose an album.", { reply_markup: inlineKeyboard([...albums.slice(0, 40).map((a) => [inlineButton(a.title, `admin:${action}:album:${a.id}`)]), [inlineButton("Back", "admin:menu")]]) }); }
composer.command("admin", async (ctx) => menu(ctx));
composer.callbackQuery("admin:menu", async (ctx) => { await ctx.answerCallbackQuery(); await menu(ctx, true); });
composer.callbackQuery("admin:create", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; ctx.session.step = "album-title"; await ctx.reply("Give the new album a title.", forceReply("Album title…")); });
composer.callbackQuery("admin:seed", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; const store = await GalleryStore.open(ctx); if (!store) return ctx.reply("Gallery storage isn't set up yet."); const added = await store.seedStarterAlbums(); if (!added) return ctx.reply("Starter albums are already in your gallery."); await notifyOwner(ctx, "Starter albums were added to the gallery.", store); await ctx.reply("Six starter albums are ready for your photos."); });
composer.callbackQuery("admin:upload", async (ctx) => { await ctx.answerCallbackQuery(); if (await owner(ctx)) await albumPicker(ctx, "upload"); });
composer.callbackQuery("admin:edit", async (ctx) => { await ctx.answerCallbackQuery(); if (await owner(ctx)) await albumPicker(ctx, "edit"); });
composer.callbackQuery("admin:delete-album", async (ctx) => { await ctx.answerCallbackQuery(); if (await owner(ctx)) await albumPicker(ctx, "delete"); });
composer.callbackQuery(/^admin:upload:album:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; ctx.session.step = "upload-file"; ctx.session.albumId = ctx.match[1]; await ctx.reply("Send a photo or image file. You can send more after each one."); });
composer.callbackQuery(/^admin:edit:album:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; const store = await GalleryStore.open(ctx), album = store && await store.album(ctx.match[1]); if (!store || !album) return ctx.reply("That album isn't available anymore."); const images = await store.images(album); if (!images.length) return ctx.reply("This album has no photos yet."); await ctx.editMessageText("Choose a photo to move or remove.", { reply_markup: inlineKeyboard([...images.map((i, n) => [inlineButton(`${n + 1}. ${i.caption || "Untitled photo"}`, `admin:image:${album.id}:${i.id}`)]), [inlineButton("Back", "admin:menu")]]) }); });
composer.callbackQuery(/^admin:image:([^:]+):(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; const [, albumId, imageId] = ctx.match; await ctx.editMessageText("Choose what to do with this photo.", { reply_markup: inlineKeyboard([[inlineButton("Move up", `admin:move:${albumId}:${imageId}:-1`), inlineButton("Move down", `admin:move:${albumId}:${imageId}:1`)], [inlineButton("Remove photo", `admin:remove:${albumId}:${imageId}`)], [inlineButton("Back", `admin:edit:album:${albumId}`)]]) }); });
composer.callbackQuery(/^admin:move:([^:]+):([^:]+):(-?1)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; const store = await GalleryStore.open(ctx), album = store && await store.album(ctx.match[1]); if (!store || !album || !(await store.reorder(album, ctx.match[2], Number(ctx.match[3]) as -1 | 1))) return ctx.reply("That photo is already at the edge."); await notifyOwner(ctx, "A photo order was updated.", store); await ctx.editMessageText("Photo order updated.", { reply_markup: inlineKeyboard([[inlineButton("Keep editing", `admin:edit:album:${album.id}`), inlineButton("Menu", "admin:menu")]]) }); });
composer.callbackQuery(/^admin:remove:([^:]+):(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; await ctx.editMessageText("Remove this photo? This can’t be undone.", { reply_markup: inlineKeyboard([[inlineButton("Remove", `admin:remove-confirm:${ctx.match[1]}:${ctx.match[2]}`), inlineButton("Keep it", `admin:edit:album:${ctx.match[1]}`)]]) }); });
composer.callbackQuery(/^admin:remove-confirm:([^:]+):(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; const store = await GalleryStore.open(ctx), album = store && await store.album(ctx.match[1]); if (!store || !album || !(await store.deleteImage(album, ctx.match[2]))) return ctx.reply("That photo isn't available anymore."); await notifyOwner(ctx, "A photo was removed from the gallery.", store); await ctx.editMessageText("Photo removed.", { reply_markup: inlineKeyboard([[inlineButton("Edit album", `admin:edit:album:${album.id}`), inlineButton("Menu", "admin:menu")]]) }); });
composer.callbackQuery(/^admin:delete:album:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; await ctx.editMessageText("Delete this album and all its photos? This can’t be undone.", { reply_markup: inlineKeyboard([[inlineButton("Delete album", `admin:delete-confirm:${ctx.match[1]}`), inlineButton("Keep it", "admin:menu")]]) }); });
composer.callbackQuery(/^admin:delete-confirm:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; const store = await GalleryStore.open(ctx), album = store && await store.album(ctx.match[1]); if (!store || !album) return ctx.reply("That album isn't available anymore."); await store.deleteAlbum(album); await notifyOwner(ctx, "An album was removed from the gallery.", store); await ctx.editMessageText("Album removed.", { reply_markup: adminKeys }); });
composer.callbackQuery("admin:notifications", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; const store = await GalleryStore.open(ctx); if (!store) return ctx.reply("Gallery storage isn't set up yet."); const enabled = await store.toggleNotifications(); await ctx.editMessageText(`Admin notifications are ${enabled ? "on" : "off"}.`, { reply_markup: adminKeys }); });
composer.on("message:photo", async (ctx, next) => { if (ctx.session.step !== "upload-file") return next(); if (!(await owner(ctx))) return; const photo = ctx.message.photo.at(-1); if (!photo || photo.file_size && photo.file_size > 10_000_000) return ctx.reply("That image is too large. Send a JPG, PNG, or WEBP under 10 MB."); ctx.session.pendingFileId = photo.file_id; ctx.session.step = "upload-caption"; await ctx.reply("Add a caption, or tap Skip.", { reply_markup: inlineKeyboard([[inlineButton("Skip", "admin:caption:skip")]]) }); });
composer.on("message:document", async (ctx, next) => { if (ctx.session.step !== "upload-file") return next(); if (!(await owner(ctx))) return; const file = ctx.message.document; if (!file.mime_type?.startsWith("image/") || file.file_size && file.file_size > 10_000_000) return ctx.reply("That file isn't an image we can use. Send a JPG, PNG, or WEBP under 10 MB."); ctx.session.pendingFileId = file.file_id; ctx.session.step = "upload-caption"; await ctx.reply("Add a caption, or tap Skip.", { reply_markup: inlineKeyboard([[inlineButton("Skip", "admin:caption:skip")]]) }); });
async function saveUpload(ctx: Ctx, tags: string) { const store = await GalleryStore.open(ctx), album = store && ctx.session.albumId && await store.album(ctx.session.albumId); if (!store || !album || !ctx.session.pendingFileId) return ctx.reply("That upload expired. Choose the album and try again."); const image = await store.addImage(album, ctx.session.pendingFileId, ctx.session.pendingCaption ?? "", tags.split(",").map(normalizeTag).filter(Boolean), String(ctx.from?.id ?? adminChatId(ctx as { env?: Record<string, unknown> }) ?? "owner")); ctx.session.step = undefined; ctx.session.pendingFileId = undefined; await notifyOwner(ctx, `A photo was added to “${album.title}”.`, store); await ctx.reply("Photo added to the album.", { reply_markup: inlineKeyboard([[inlineButton("Add another", `admin:upload:album:${album.id}`), inlineButton("View album", `album:view:${album.id}`)]]) }); return image; }
composer.callbackQuery("admin:caption:skip", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; ctx.session.pendingCaption = ""; ctx.session.step = "upload-tags"; await ctx.reply("Add tags separated by commas, or tap Skip.", { reply_markup: inlineKeyboard([[inlineButton("Skip", "admin:tags:skip")]]) }); });
composer.callbackQuery("admin:tags:skip", async (ctx) => { await ctx.answerCallbackQuery(); if (await owner(ctx)) await saveUpload(ctx, ""); });
composer.on("message:text", async (ctx, next) => { if (!ctx.session.step?.startsWith("album-") && !ctx.session.step?.startsWith("upload-")) return next(); if (!(await owner(ctx))) return; const text = ctx.message.text.trim(); if (ctx.session.step === "album-title") { if (!text) return ctx.reply("Give the album a short title to continue."); ctx.session.pendingTitle = text.slice(0, 100); ctx.session.step = "album-description"; return ctx.reply("Add a short description, or tap Skip.", { reply_markup: inlineKeyboard([[inlineButton("Skip", "admin:description:skip")]]) }); } if (ctx.session.step === "album-description") { const store = await GalleryStore.open(ctx); if (!store || !ctx.session.pendingTitle) return ctx.reply("That draft expired. Start the album again."); const album = await store.createAlbum(ctx.session.pendingTitle, text.slice(0, 500)); ctx.session.step = undefined; await notifyOwner(ctx, `Album “${album.title}” was created.`, store); return ctx.reply("Album created. You can add photos now.", { reply_markup: inlineKeyboard([[inlineButton("Upload photos", `admin:upload:album:${album.id}`), inlineButton("Menu", "admin:menu")]]) }); } if (ctx.session.step === "upload-caption") { ctx.session.pendingCaption = text.slice(0, 1024); ctx.session.step = "upload-tags"; return ctx.reply("Add tags separated by commas, or tap Skip.", { reply_markup: inlineKeyboard([[inlineButton("Skip", "admin:tags:skip")]]) }); } if (ctx.session.step === "upload-tags") return saveUpload(ctx, text); return next(); });
composer.callbackQuery("admin:description:skip", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; const store = await GalleryStore.open(ctx); if (!store || !ctx.session.pendingTitle) return ctx.reply("That draft expired. Start the album again."); const album = await store.createAlbum(ctx.session.pendingTitle, ""); ctx.session.step = undefined; await notifyOwner(ctx, `Album “${album.title}” was created.`, store); await ctx.reply("Album created. You can add photos now.", { reply_markup: inlineKeyboard([[inlineButton("Upload photos", `admin:upload:album:${album.id}`)]]) }); });
export default composer;
